### ISSUE TITLE
Github 项目推荐 第一期

### ISSUE THREAD

**Issue by uuPin1** [uuPin1/http#23]
目的是为了增添更多交流互动。

- [Octotree](https://github.com/buunguyen/octotree)： github plugin，快速在线阅读github代码工具。- Ps 
- [nodeppt](https://github.com/ksky521/nodePPT)： 很好用的PPT工具 - Ps
- [awesome](https://github.com/sindresorhus/awesome)：  各种类型的资源汇总- 游里
- [free-programming-books](https://github.com/vhf/free-programming-books)： 免费的编程向电子书- 游里
- [typo.css](https://github.com/sofish/typo.css)： 很适合中文阅读的网页排版- 游里
- [slick](https://github.com/kenwheeler/slick)： 很好用的轮播插件- 游里
- [skill-map](https://github.com/TeamStuQ/skill-map)： 技能图谱 - 游里

**Comment by Colafornia** [comment]
算法：
- [AlgorithmVisualizer](https://github.com/parkjs814/AlgorithmVisualizer) 一个算法可视化项目，除此之外有一个[网站](https://zh.visualgo.net/)也很不错

JavaScript 相关：

- [一个源码阅读工具](https://github.com/Jianru-Lin/lambda-view) 支持语法(包括ES6)高亮，方便看结构，尤其方便在移动端(iPad)上没有IDE的时候使用
- [You-Dont-Need-JavaScript](https://github.com/you-dont-need/You-Dont-Need-Javascript) 开阔思路，很多场景不需要用JS来控制
- [You-Dont-Need-jQuery](https://github.com/oneuijs/You-Dont-Need-jQuery) 抛弃冗余，拥抱高性能

最后私心推荐一个 [jQuery源代码查看工具](http://www.css88.com/tool/jQuerySourceViewer/) 可以按照版本，函数，方法来查看源码

**Comment by uuPin1** [comment]
[yoga](https://github.com/facebook/yoga) - Chihiro
react native的布局使用的是Yoga(之前叫CssLayout)，核心代码就6个文件。现在做跨平台布局（iOS、Android、H5、PC），很多人都会优先研究这个。我们目前也是基于这个布局搭建自己的跨平台布局：）

**Comment by uuPin1** [comment]
[PanoramaImageView](https://github.com/gjiazhe/PanoramaImageView) - Chihiro
